@api = http://localhost:3000/api

# @name authenticate
POST {{api}}/users/authenticate
Content-Type: application/json

{
    "username": "admin",
    "password": "root"
}

### GET USERS
GET {{api}}/users
Authorization: Bearer {{authenticate.response.body.accessToken}}

### CREATE ORDER
POST {{api}}/orders
Content-Type: application/json
Authorization: Bearer {{authenticate.response.body.accessToken}}

{
    "item": {
        "product_id": 1,
        "quantity":1,
        "engraving": "custom engraving"
    },
    "comments": "new order",
    "calledAt": 1638044955061
}